name: PMIS-CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh
      - name: Install & test
        run: |
          uv pip install -r requirements.txt --system
          pytest tests/
      - name: Start API & smoke test
        run: |
          uvicorn api.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl -f http://localhost:8000/predict